var1 = input('Digite algo:')
print('O tipo primitivo desse valor é', type(var1))
print('é alfanumérico?', var1.isalnum())
print('é alfabético?', var1.isalpha())
print('é um número?', var1.isnumeric())
print('está somente em letras maiúsculas?', var1.isupper())
print('só tem espaço?', var1.isspace())
print('está em maiúsculas?', var1.isupper())
print('está em minúsculas?', var1.islower())
